sudo: required
os: osx
osx_image: xcode10.2
services:
  - docker

before_install:
  - docker build -t skilaru/docker-react -f Dockerfile.dev .

script:
  - docker run skilaru/docker-react npm run test -- --coverage